title: Operating System Programming 4DISS
description: (V187-20220220).
      This site has been managed by VauLSMorg (vlsm.org) since 2020.
      <br>May the fork() be with Jolan Tru! --- rms46 (@T) ui dot ac dot id.
google_analytics: UA-89852122-8
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permited here.
author: Mr. Y. Yoda
show_downloads: false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/os2xx/osp4diss/

# github:
#    zip_url: https://github.com/rms46/...
#    tar_url: https://github.com/rms46/...

github: [metadata]

